In [2]:
# Import pandas for data manipulation and analysis
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Import os for file and folder operations
import os

# Ignore unnecessary warning messages
import warnings
warnings.filterwarnings("ignore")

# Confirm successful import
print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
# Define the path to the data folder
DATA_PATH = "../data"

# Define the path where the processed dataset will be saved
PROCESSED_PATH = "../data"

# Display the paths
print("Data path:", DATA_PATH)
print("Processed data path:", PROCESSED_PATH)

Data path: ../data
Processed data path: ../data

In [6]:
# Load all tourism datasets

user_df = pd.read_excel("../data/User.xlsx")
type_df = pd.read_excel("../data/Type.xlsx")
transaction_df = pd.read_excel("../data/Transaction.xlsx")
region_df = pd.read_excel("../data/Region.xlsx")
mode_df = pd.read_excel("../data/Mode.xlsx")
item_df = pd.read_excel("../data/Item.xlsx")
country_df = pd.read_excel("../data/Country.xlsx")
continent_df = pd.read_excel("../data/Continent.xlsx")
city_df = pd.read_excel("../data/City.xlsx")

# Load the additional attraction-site dataset
attraction_df = pd.read_excel("../data/Updated_Item.xlsx")

# Confirm successful loading
print("All datasets loaded successfully!")

All datasets loaded successfully!

In [7]:
# Display the number of rows and columns in each dataset

print("User:", user_df.shape)
print("Type:", type_df.shape)
print("Transaction:", transaction_df.shape)
print("Region:", region_df.shape)
print("Mode:", mode_df.shape)
print("Item:", item_df.shape)
print("Country:", country_df.shape)
print("Continent:", continent_df.shape)
print("City:", city_df.shape)
print("Attraction:", attraction_df.shape)

User: (33530, 5)
Type: (17, 2)
Transaction: (52930, 7)
Region: (22, 3)
Mode: (6, 2)
Item: (30, 5)
Country: (165, 3)
Continent: (6, 2)
City: (9143, 3)
Attraction: (1698, 5)

In [8]:
# Display users whose CityId is missing

missing_city_users = user_df[user_df["CityId"].isna()]

display(missing_city_users)

       UserId  ContinentId  RegionId  CountryId  CityId
2279     7175            5        17        135     NaN
6027    17595            1         4         22     NaN
21303   56972            5        17        135     NaN
25494   67461            5        17        135     NaN

In [9]:
# Display the city record where CityName is missing

missing_city_record = city_df[city_df["CityName"].isna()]

display(missing_city_record)

      CityId CityName  CountryId
6879    6879      NaN        151

In [10]:
# Check and standardize ID columns only when they contain numeric IDs
# We will NOT force AttractionTypeId in the additional attraction file
# to integer because our EDA showed that this column contains text values.

# User dataset
user_df["UserId"] = pd.to_numeric(user_df["UserId"], errors="coerce").astype("Int64")
user_df["ContinentId"] = pd.to_numeric(user_df["ContinentId"], errors="coerce").astype("Int64")
user_df["RegionId"] = pd.to_numeric(user_df["RegionId"], errors="coerce").astype("Int64")
user_df["CountryId"] = pd.to_numeric(user_df["CountryId"], errors="coerce").astype("Int64")
user_df["CityId"] = pd.to_numeric(user_df["CityId"], errors="coerce").astype("Int64")

# Transaction dataset
transaction_df["TransactionId"] = pd.to_numeric(
    transaction_df["TransactionId"], errors="coerce"
).astype("Int64")

transaction_df["UserId"] = pd.to_numeric(
    transaction_df["UserId"], errors="coerce"
).astype("Int64")

transaction_df["AttractionId"] = pd.to_numeric(
    transaction_df["AttractionId"], errors="coerce"
).astype("Int64")

# Type dataset
type_df["AttractionTypeId"] = pd.to_numeric(
    type_df["AttractionTypeId"], errors="coerce"
).astype("Int64")

# Region dataset
region_df["RegionId"] = pd.to_numeric(
    region_df["RegionId"], errors="coerce"
).astype("Int64")

region_df["ContinentId"] = pd.to_numeric(
    region_df["ContinentId"], errors="coerce"
).astype("Int64")

# Mode dataset
mode_df["VisitModeId"] = pd.to_numeric(
    mode_df["VisitModeId"], errors="coerce"
).astype("Int64")

# Item dataset
item_df["AttractionId"] = pd.to_numeric(
    item_df["AttractionId"], errors="coerce"
).astype("Int64")

item_df["AttractionCityId"] = pd.to_numeric(
    item_df["AttractionCityId"], errors="coerce"
).astype("Int64")

item_df["AttractionTypeId"] = pd.to_numeric(
    item_df["AttractionTypeId"], errors="coerce"
).astype("Int64")

# Country dataset
country_df["CountryId"] = pd.to_numeric(
    country_df["CountryId"], errors="coerce"
).astype("Int64")

country_df["RegionId"] = pd.to_numeric(
    country_df["RegionId"], errors="coerce"
).astype("Int64")

# Continent dataset
continent_df["ContinentId"] = pd.to_numeric(
    continent_df["ContinentId"], errors="coerce"
).astype("Int64")

# City dataset
city_df["CityId"] = pd.to_numeric(
    city_df["CityId"], errors="coerce"
).astype("Int64")

city_df["CountryId"] = pd.to_numeric(
    city_df["CountryId"], errors="coerce"
).astype("Int64")

# Additional attraction-site dataset
# Keep AttractionTypeId unchanged for now because it contains text
# such as "Temple" and therefore is not a numeric ID in this file.

attraction_df["AttractionId"] = pd.to_numeric(
    attraction_df["AttractionId"], errors="coerce"
).astype("Int64")

attraction_df["AttractionCityId"] = pd.to_numeric(
    attraction_df["AttractionCityId"], errors="coerce"
).astype("Int64")

print("ID columns standardized safely!")

ID columns standardized safely!

In [11]:
# Verify the important ID columns after conversion

print("User CityId:", user_df["CityId"].dtype)
print("Transaction UserId:", transaction_df["UserId"].dtype)
print("Transaction AttractionId:", transaction_df["AttractionId"].dtype)
print("Attraction TypeId:", attraction_df["AttractionTypeId"].dtype)
print("City CityId:", city_df["CityId"].dtype)

User CityId: Int64
Transaction UserId: Int64
Transaction AttractionId: Int64
Attraction TypeId: object
City CityId: Int64

In [12]:
# Start the master dataset with transaction records

master_df = transaction_df.copy()

# Display the initial shape
print("Initial master dataset shape:", master_df.shape)

Initial master dataset shape: (52930, 7)

In [13]:
# Merge transaction data with user information
# UserId is the common key between the two datasets

master_df = master_df.merge(
    user_df,
    on="UserId",
    how="left"
)

# Display the updated shape
print("After merging User:", master_df.shape)

After merging User: (52930, 11)

In [14]:
# Merge attraction information using AttractionId

master_df = master_df.merge(
    attraction_df,
    on="AttractionId",
    how="left"
)

# Display the updated shape
print("After merging Attraction:", master_df.shape)

After merging Attraction: (52930, 15)

In [16]:
# Merge attraction type information
# AttractionTypeId connects Attraction with Type

master_df = master_df.merge(
    type_df,
    on="AttractionTypeId",
    how="left"
)

print("After merging Attraction Type:", master_df.shape)

After merging Attraction Type: (52930, 17)

In [17]:
# Select only the required columns from the Mode dataset
# This prevents duplicate VisitMode columns after merging

mode_lookup = mode_df[
    ["VisitModeId", "VisitMode"]
].copy()

# Rename the descriptive column so it is clear in the final dataset
mode_lookup = mode_lookup.rename(
    columns={"VisitMode": "VisitModeName"}
)

# Merge transaction data with visit mode information
# Transaction.VisitMode → Mode.VisitModeId

master_df = master_df.merge(
    mode_lookup,
    left_on="VisitMode",
    right_on="VisitModeId",
    how="left"
)

# Display the updated shape
print("After merging Visit Mode:", master_df.shape)

# Display the mapping to verify the merge
display(
    master_df[
        ["VisitMode", "VisitModeId", "VisitModeName"]
    ].head(10)
)

After merging Visit Mode: (52930, 19)

   VisitMode  VisitModeId VisitModeName
0          2            2       Couples
1          4            4       Friends
2          3            3        Family
3          3            3        Family
4          2            2       Couples
5          4            4       Friends
6          2            2       Couples
7          4            4       Friends
8          2            2       Couples
9          2            2       Couples

In [22]:
# Check whether all VisitMode values found a matching VisitModeName

missing_visit_modes = master_df["VisitModeName"].isna().sum()

print("Records without a matching Visit Mode:", missing_visit_modes)

display(
    master_df[
        ["VisitMode", "VisitModeId", "VisitModeName"]
    ].head(10)
)

Records without a matching Visit Mode: 0

   VisitMode  VisitModeId VisitModeName
0          2            2       Couples
1          4            4       Friends
2          3            3        Family
3          3            3        Family
4          2            2       Couples
5          4            4       Friends
6          2            2       Couples
7          4            4       Friends
8          2            2       Couples
9          2            2       Couples

# Merge City Information

# AttractionCityId → CityId → CityName

In [23]:
# Select required columns from City dataset

city_lookup = city_df[
    ["CityId", "CityName"]
].drop_duplicates("CityId")

# Merge City information using AttractionCityId

master_df = master_df.merge(
    city_lookup,
    left_on="AttractionCityId",
    right_on="CityId",
    how="left",
    suffixes=("", "_City"),
    validate="many_to_one"
)

# Remove duplicate CityId created by the merge

master_df = master_df.drop(columns=["CityId_City"])

print("After merging City:", master_df.shape)

display(
    master_df[
        ["AttractionCityId", "CityId", "CityName"]
    ].head(10)
)

After merging City: (52930, 20)

   AttractionCityId  CityId CityName
0                 1    4341   Douala
1                 1     464   Douala
2                 1     774   Douala
3                 1     583   Douala
4                 1    1396   Douala
5                 1    1806   Douala
6                 1      31   Douala
7                 1    8258   Douala
8                 1     114   Douala
9                 1      50   Douala

In [24]:
# Check whether all attractions found a matching city

missing_city = master_df["CityName"].isna().sum()

print("Records without a matching City:", missing_city)

Records without a matching City: 0

In [25]:
# Select required columns from Country dataset

country_lookup = country_df[
    ["CountryId", "Country", "RegionId"]
].drop_duplicates("CountryId")

# Merge Country information

master_df = master_df.merge(
    country_lookup,
    on="CountryId",
    how="left",
    suffixes=("", "_Country"),
    validate="many_to_one"
)

print("After merging Country:", master_df.shape)

display(
    master_df[
        ["CountryId", "Country"]
    ].head(10)
)

After merging Country: (52930, 22)

   CountryId         Country
0        163  United Kingdom
1         48          Canada
2         54          Brazil
3        135     Switzerland
4        163  United Kingdom
5         51   United States
6          9        Tanzania
7        163  United Kingdom
8         22    South Africa
9         51   United States

In [26]:
# Check whether all records found a matching country

missing_country = master_df["Country"].isna().sum()

print("Records without a matching Country:", missing_country)

Records without a matching Country: 0

In [27]:
# Replace the original RegionId with the RegionId
# obtained from the Country dataset

if "RegionId_Country" in master_df.columns:
    master_df["RegionId"] = master_df["RegionId_Country"]
    master_df = master_df.drop(columns=["RegionId_Country"])

print("RegionId updated successfully!")

display(
    master_df[
        ["CountryId", "Country", "RegionId"]
    ].head(10)
)

RegionId updated successfully!

   CountryId         Country  RegionId
0        163  United Kingdom        21
1         48          Canada         8
2         54          Brazil         9
3        135     Switzerland        17
4        163  United Kingdom        21
5         51   United States         8
6          9        Tanzania         2
7        163  United Kingdom        21
8         22    South Africa         4
9         51   United States         8

In [28]:
# Select required columns from Region dataset

region_lookup = region_df[
    ["RegionId", "Region", "ContinentId"]
].drop_duplicates("RegionId")

# Merge Region information

master_df = master_df.merge(
    region_lookup,
    on="RegionId",
    how="left",
    suffixes=("", "_Region"),
    validate="many_to_one"
)

print("After merging Region:", master_df.shape)

display(
    master_df[
        ["RegionId", "Region"]
    ].head(10)
)

After merging Region: (52930, 23)

   RegionId            Region
0        21    Western Europe
1         8  Northern America
2         9     South America
3        17    Central Europe
4        21    Western Europe
5         8  Northern America
6         2       East Africa
7        21    Western Europe
8         4   Southern Africa
9         8  Northern America

In [29]:
# Check whether all records found a matching region

missing_region = master_df["Region"].isna().sum()

print("Records without a matching Region:", missing_region)

Records without a matching Region: 0

In [30]:
# Replace the original ContinentId with the
# ContinentId obtained from the Region dataset

if "ContinentId_Region" in master_df.columns:
    master_df["ContinentId"] = master_df["ContinentId_Region"]
    master_df = master_df.drop(columns=["ContinentId_Region"])

print("ContinentId updated successfully!")

display(
    master_df[
        ["RegionId", "Region", "ContinentId"]
    ].head(10)
)

ContinentId updated successfully!

   RegionId            Region  ContinentId
0        21    Western Europe            5
1         8  Northern America            2
2         9     South America            2
3        17    Central Europe            5
4        21    Western Europe            5
5         8  Northern America            2
6         2       East Africa            1
7        21    Western Europe            5
8         4   Southern Africa            1
9         8  Northern America            2

In [31]:
# Select required columns from Continent dataset

continent_lookup = continent_df[
    ["ContinentId", "Continent"]
].drop_duplicates("ContinentId")

# Merge Continent information

master_df = master_df.merge(
    continent_lookup,
    on="ContinentId",
    how="left",
    validate="many_to_one"
)

print("After merging Continent:", master_df.shape)

display(
    master_df[
        ["ContinentId", "Continent"]
    ].head(10)
)

After merging Continent: (52930, 23)

   ContinentId Continent
0            5    Europe
1            2   America
2            2   America
3            5    Europe
4            5    Europe
5            2   America
6            1    Africa
7            5    Europe
8            1    Africa
9            2   America

In [32]:
# Check whether all records found a matching continent

missing_continent = master_df["Continent"].isna().sum()

print("Records without a matching Continent:", missing_continent)

Records without a matching Continent: 0

In [33]:
# Check the final structure after all major merges

print("Final merged dataset shape:", master_df.shape)

print("\nColumns:")
print(master_df.columns.tolist())

display(master_df.head(10))

Final merged dataset shape: (52930, 23)

Columns:
['TransactionId', 'UserId', 'VisitYear', 'VisitMonth', 'VisitMode', 'AttractionId', 'Rating', 'ContinentId', 'RegionId', 'CountryId', 'CityId', 'AttractionCityId', 'AttractionTypeId', 'Attraction', 'AttractionAddress', 'AttractionType_x', 'AttractionType_y', 'VisitModeId', 'VisitModeName', 'CityName', 'Country', 'Region', 'Continent']

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating,ContinentId,RegionId,CountryId,...,Attraction,AttractionAddress,AttractionType_x,AttractionType_y,VisitModeId,VisitModeName,CityName,Country,Region,Continent
0,3,70456,2022,10,2,640,5,5,21,163,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe
1,8,7567,2022,10,4,640,5,2,8,48,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,4,Friends,Douala,Canada,Northern America,America
2,9,79069,2022,10,3,640,5,2,9,54,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,3,Family,Douala,Brazil,South America,America
3,10,31019,2022,10,3,640,3,5,17,135,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,3,Family,Douala,Switzerland,Central Europe,Europe
4,15,43611,2022,10,2,640,3,5,21,163,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe
5,18,43471,2022,10,4,640,5,2,8,51,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,4,Friends,Douala,United States,Northern America,America
6,22,76492,2022,9,2,640,4,1,2,9,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,2,Couples,Douala,Tanzania,East Africa,Africa
7,23,20977,2022,10,4,640,5,5,21,163,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,4,Friends,Douala,United Kingdom,Western Europe,Europe
8,28,18655,2022,9,2,640,3,1,4,22,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,2,Couples,Douala,South Africa,Southern Africa,Africa
9,29,62907,2022,9,2,640,5,2,8,51,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,2,Couples,Douala,United States,Northern America,America

In [34]:
# Check missing values in the merged dataset

missing_summary = master_df.isnull().sum()

missing_summary = missing_summary[
    missing_summary > 0
].sort_values(ascending=False)

print("Columns with missing values:")

display(missing_summary)

Columns with missing values:

CityId    8
dtype: int64

In [35]:
# Display rows containing missing values

missing_rows = master_df[
    master_df.isnull().any(axis=1)
]

print("Number of rows containing missing values:", len(missing_rows))

display(missing_rows.head(10))

Number of rows containing missing values: 8

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating,ContinentId,RegionId,CountryId,...,Attraction,AttractionAddress,AttractionType_x,AttractionType_y,VisitModeId,VisitModeName,CityName,Country,Region,Continent
7134,10437,7175,2016,10,5,640,5,5,17,135,...,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Nature & Wildlife Areas,5,Solo,Douala,Switzerland,Central Europe,Europe
21190,33604,56972,2016,12,2,673,4,5,17,135,...,Seminyak Beach,Seminyak,Beaches,Beaches,2,Couples,Douala,Switzerland,Central Europe,Europe
22283,35006,17595,2014,12,3,673,4,1,4,22,...,Seminyak Beach,Seminyak,Beaches,Beaches,3,Family,Douala,South Africa,Southern Africa,Africa
26249,42487,56972,2016,12,2,650,5,5,17,135,...,Sanur Beach,Sanur,Beaches,Beaches,2,Couples,Douala,Switzerland,Central Europe,Europe
31689,67298,67461,2019,5,4,748,5,5,17,135,...,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Points of Interest & Landmarks,4,Friends,Douala,Switzerland,Central Europe,Europe
34600,71286,56972,2016,12,2,748,5,5,17,135,...,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Points of Interest & Landmarks,2,Couples,Douala,Switzerland,Central Europe,Europe
34799,71574,7175,2016,10,5,748,5,5,17,135,...,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Points of Interest & Landmarks,5,Solo,Douala,Switzerland,Central Europe,Europe
36610,74011,17595,2014,12,3,748,5,1,4,22,...,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Points of Interest & Landmarks,3,Family,Douala,South Africa,Southern Africa,Africa

In [36]:
# Check remaining missing values

missing_summary = master_df.isnull().sum()

missing_summary = missing_summary[
    missing_summary > 0
].sort_values(ascending=False)

print("Columns with missing values:")

display(missing_summary)

Columns with missing values:

CityId    8
dtype: int64

In [37]:
# Remove rows where essential tourism information is missing

before_rows = len(master_df)

master_df = master_df.dropna(
    subset=[
        "AttractionId",
        "AttractionCityId",
        "CityName",
        "Country",
        "Region",
        "Continent"
    ]
)

after_rows = len(master_df)

print("Rows before removing missing essential values:", before_rows)
print("Rows after removing missing essential values:", after_rows)
print("Rows removed:", before_rows - after_rows)

Rows before removing missing essential values: 52930
Rows after removing missing essential values: 52930
Rows removed: 0

In [38]:
# Verify remaining missing values

remaining_missing = master_df.isnull().sum()

remaining_missing = remaining_missing[
    remaining_missing > 0
].sort_values(ascending=False)

print("Remaining missing values:")

display(remaining_missing)

Remaining missing values:

CityId    8
dtype: int64

In [39]:
# Check duplicate Attraction Type columns

if "AttractionType_x" in master_df.columns and "AttractionType_y" in master_df.columns:

    same_percentage = (
        master_df["AttractionType_x"].astype(str)
        ==
        master_df["AttractionType_y"].astype(str)
    ).mean() * 100

    print(
        f"AttractionType columns have {same_percentage:.2f}% matching values."
    )

AttractionType columns have 100.00% matching values.

In [40]:
# Keep one AttractionType column

master_df = master_df.drop(
    columns=["AttractionType_y"]
)

master_df = master_df.rename(
    columns={
        "AttractionType_x": "AttractionType"
    }
)

print("Duplicate AttractionType column removed.")

display(
    master_df[
        [
            "AttractionId",
            "AttractionTypeId",
            "Attraction",
            "AttractionType"
        ]
    ].head(10)
)

Duplicate AttractionType column removed.

,AttractionId,AttractionTypeId,Attraction,AttractionType
0,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
1,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
2,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
3,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
4,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
5,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
6,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
7,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
8,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas
9,640,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas

In [41]:
# Keep the descriptive VisitMode name
# and remove the duplicate numeric VisitMode column

master_df = master_df.drop(
    columns=["VisitMode"]
)

master_df = master_df.rename(
    columns={
        "VisitModeId": "VisitModeID",
        "VisitModeName": "VisitMode"
    }
)

print("Visit Mode columns cleaned.")

display(
    master_df[
        ["VisitModeID", "VisitMode"]
    ].head(10)
)

Visit Mode columns cleaned.

   VisitModeID VisitMode
0            2   Couples
1            4   Friends
2            3    Family
3            3    Family
4            2   Couples
5            4   Friends
6            2   Couples
7            4   Friends
8            2   Couples
9            2   Couples

In [42]:
# Create a proper VisitDate column

master_df["VisitDate"] = pd.to_datetime(
    master_df["VisitYear"].astype(str)
    + "-"
    + master_df["VisitMonth"].astype(str)
    + "-01",
    errors="coerce"
)

display(
    master_df[
        ["VisitYear", "VisitMonth", "VisitDate"]
    ].head(10)
)

   VisitYear  VisitMonth  VisitDate
0       2022          10 2022-10-01
1       2022          10 2022-10-01
2       2022          10 2022-10-01
3       2022          10 2022-10-01
4       2022          10 2022-10-01
5       2022          10 2022-10-01
6       2022           9 2022-09-01
7       2022          10 2022-10-01
8       2022           9 2022-09-01
9       2022           9 2022-09-01

In [43]:
# Create rating categories

def classify_rating(rating):

    if rating <= 2:
        return "Low"

    elif rating == 3:
        return "Average"

    else:
        return "High"


master_df["RatingCategory"] = master_df["Rating"].apply(
    classify_rating
)

display(
    master_df[
        ["Rating", "RatingCategory"]
    ].head(10)
)

   Rating RatingCategory
0       5           High
1       5           High
2       5           High
3       3        Average
4       3        Average
5       5           High
6       4           High
7       5           High
8       3        Average
9       5           High

In [44]:
# Create Year-Month column for time-based analysis

master_df["VisitYearMonth"] = (
    master_df["VisitDate"]
    .dt.to_period("M")
    .astype(str)
)

display(
    master_df[
        ["VisitDate", "VisitYearMonth"]
    ].head(10)
)

   VisitDate VisitYearMonth
0 2022-10-01        2022-10
1 2022-10-01        2022-10
2 2022-10-01        2022-10
3 2022-10-01        2022-10
4 2022-10-01        2022-10
5 2022-10-01        2022-10
6 2022-09-01        2022-09
7 2022-10-01        2022-10
8 2022-09-01        2022-09
9 2022-09-01        2022-09

In [45]:
# Check duplicate records in the final dataset

duplicate_count = master_df.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

In [46]:
# Check final data types

print("Final data types:")

display(
    master_df.dtypes.to_frame("Data Type")
)

Final data types:

                        Data Type
TransactionId               Int64
UserId                      Int64
VisitYear                   int64
VisitMonth                  int64
AttractionId                Int64
Rating                      int64
ContinentId                 Int64
RegionId                    Int64
CountryId                   Int64
CityId                      Int64
AttractionCityId            Int64
AttractionTypeId           object
Attraction                    str
AttractionAddress             str
AttractionType                str
VisitModeID                 Int64
VisitMode                     str
CityName                      str
Country                       str
Region                        str
Continent                     str
VisitDate          datetime64[us]
RatingCategory                str
VisitYearMonth                str

In [47]:
# Final missing-value check

final_missing = master_df.isnull().sum()

final_missing = final_missing[
    final_missing > 0
].sort_values(ascending=False)

print("Final missing values:")

if len(final_missing) == 0:
    print("No missing values remaining!")
else:
    display(final_missing)

Final missing values:

CityId    8
dtype: int64

In [48]:
# Preview the cleaned dataset

display(
    master_df.head(10)
)

,TransactionId,UserId,VisitYear,VisitMonth,AttractionId,Rating,ContinentId,RegionId,CountryId,CityId,...,AttractionType,VisitModeID,VisitMode,CityName,Country,Region,Continent,VisitDate,RatingCategory,VisitYearMonth
0,3,70456,2022,10,640,5,5,21,163,4341,...,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe,2022-10-01,High,2022-10
1,8,7567,2022,10,640,5,2,8,48,464,...,Nature & Wildlife Areas,4,Friends,Douala,Canada,Northern America,America,2022-10-01,High,2022-10
2,9,79069,2022,10,640,5,2,9,54,774,...,Nature & Wildlife Areas,3,Family,Douala,Brazil,South America,America,2022-10-01,High,2022-10
3,10,31019,2022,10,640,3,5,17,135,583,...,Nature & Wildlife Areas,3,Family,Douala,Switzerland,Central Europe,Europe,2022-10-01,Average,2022-10
4,15,43611,2022,10,640,3,5,21,163,1396,...,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe,2022-10-01,Average,2022-10
5,18,43471,2022,10,640,5,2,8,51,1806,...,Nature & Wildlife Areas,4,Friends,Douala,United States,Northern America,America,2022-10-01,High,2022-10
6,22,76492,2022,9,640,4,1,2,9,31,...,Nature & Wildlife Areas,2,Couples,Douala,Tanzania,East Africa,Africa,2022-09-01,High,2022-09
7,23,20977,2022,10,640,5,5,21,163,8258,...,Nature & Wildlife Areas,4,Friends,Douala,United Kingdom,Western Europe,Europe,2022-10-01,High,2022-10
8,28,18655,2022,9,640,3,1,4,22,114,...,Nature & Wildlife Areas,2,Couples,Douala,South Africa,Southern Africa,Africa,2022-09-01,Average,2022-09
9,29,62907,2022,9,640,5,2,8,51,50,...,Nature & Wildlife Areas,2,Couples,Douala,United States,Northern America,America,2022-09-01,High,2022-09

In [49]:
# Check final dataset dimensions

print("Final number of rows:", master_df.shape[0])
print("Final number of columns:", master_df.shape[1])

Final number of rows: 52930
Final number of columns: 24

In [50]:
# Save the processed dataset

output_file = "../data/tourism_experience_processed.csv"

master_df.to_csv(
    output_file,
    index=False
)

print("Processed dataset saved successfully!")
print("File:", output_file)

Processed dataset saved successfully!
File: ../data/tourism_experience_processed.csv

In [51]:
# Verify that the processed file exists

import os

if os.path.exists(output_file):
    print("File successfully created!")
    print("File size:", round(os.path.getsize(output_file) / (1024 * 1024), 2), "MB")
else:
    print("File was not created.")

File successfully created!
File size: 9.88 MB

In [52]:
# Reload the processed dataset

processed_df = pd.read_csv(
    output_file
)

print("Processed dataset loaded successfully!")

print("Shape:", processed_df.shape)

display(
    processed_df.head(10)
)

Processed dataset loaded successfully!
Shape: (52930, 24)

,TransactionId,UserId,VisitYear,VisitMonth,AttractionId,Rating,ContinentId,RegionId,CountryId,CityId,...,AttractionType,VisitModeID,VisitMode,CityName,Country,Region,Continent,VisitDate,RatingCategory,VisitYearMonth
0,3,70456,2022,10,640,5,5,21,163,4341.0,...,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe,2022-10-01,High,2022-10
1,8,7567,2022,10,640,5,2,8,48,464.0,...,Nature & Wildlife Areas,4,Friends,Douala,Canada,Northern America,America,2022-10-01,High,2022-10
2,9,79069,2022,10,640,5,2,9,54,774.0,...,Nature & Wildlife Areas,3,Family,Douala,Brazil,South America,America,2022-10-01,High,2022-10
3,10,31019,2022,10,640,3,5,17,135,583.0,...,Nature & Wildlife Areas,3,Family,Douala,Switzerland,Central Europe,Europe,2022-10-01,Average,2022-10
4,15,43611,2022,10,640,3,5,21,163,1396.0,...,Nature & Wildlife Areas,2,Couples,Douala,United Kingdom,Western Europe,Europe,2022-10-01,Average,2022-10
5,18,43471,2022,10,640,5,2,8,51,1806.0,...,Nature & Wildlife Areas,4,Friends,Douala,United States,Northern America,America,2022-10-01,High,2022-10
6,22,76492,2022,9,640,4,1,2,9,31.0,...,Nature & Wildlife Areas,2,Couples,Douala,Tanzania,East Africa,Africa,2022-09-01,High,2022-09
7,23,20977,2022,10,640,5,5,21,163,8258.0,...,Nature & Wildlife Areas,4,Friends,Douala,United Kingdom,Western Europe,Europe,2022-10-01,High,2022-10
8,28,18655,2022,9,640,3,1,4,22,114.0,...,Nature & Wildlife Areas,2,Couples,Douala,South Africa,Southern Africa,Africa,2022-09-01,Average,2022-09
9,29,62907,2022,9,640,5,2,8,51,50.0,...,Nature & Wildlife Areas,2,Couples,Douala,United States,Northern America,America,2022-09-01,High,2022-09

In [53]:
# Final preprocessing summary

print("========================================")
print("   PREPROCESSING COMPLETED SUCCESSFULLY")
print("========================================")

print("\nFinal dataset shape:")
print(master_df.shape)

print("\nNumber of records:")
print(len(master_df))

print("\nNumber of features:")
print(len(master_df.columns))

print("\nDuplicate records:")
print(master_df.duplicated().sum())

print("\nMissing values:")
print(master_df.isnull().sum().sum())

print("\nProcessed file:")
print(output_file)

========================================
   PREPROCESSING COMPLETED SUCCESSFULLY
========================================

Final dataset shape:
(52930, 24)

Number of records:
52930

Number of features:
24

Duplicate records:
0

Missing values:
8

Processed file:
../data/tourism_experience_processed.csv